### ISSUE TITLE
update `violin_plot()` in graphs.py

### ISSUE THREAD

**Issue by zobelj** [zobelj/MarchMadnessAuction#6]
`violin_plot()` in graphs.py is currently hardcoded to create a violin plot of player points using pre-tournament projections

- add an option for the following:
    - use latest sims (including real results) from the `march_madness` table
    - use pre-tournament projections from the `march_madness_pre` table
- add an option for showing team (school) violin plots:
    - using latest sims
    - using pre-tournament projections

take a look at  `lib/database/run_query()` instead of using the current process

**Comment by jeremyfrank333** [comment]
will take a look, thx

**Comment by zobelj** [comment]
Resolved in #11
